/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.BorderLayout;
import paneles.JPanelBusquedaCliente;
import paneles.JPanelIngresoAbonos;
import paneles.JPanelListadoClienteCredito;
import paneles.JPanelModClienteCredito;
import paneles.JPanelNuevoClienteCredito;

/**
 *
 * @author Psinergia
 */
public class LineaCredito extends javax.swing.JInternalFrame {

    /**
     * Creates new form LineaCredito
     */
    public LineaCredito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnListadoClientes = new javax.swing.JButton();
        BtnRegistroClientes = new javax.swing.JButton();
        BtnModCliente = new javax.swing.JButton();
        btnEliminar2 = new javax.swing.JButton();
        BtnUltimosPagos = new javax.swing.JButton();
        BtnBusquedaCliente = new javax.swing.JButton();
        btnAbonos = new javax.swing.JButton();
        btnAbonos1 = new javax.swing.JButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        JPanelcambianteLineaCredito = new javax.swing.JPanel();

        jInternalFrame1.setBackground(new java.awt.Color(88, 147, 191));
        jInternalFrame1.setVisible(true);

        jPanel5.setBackground(new java.awt.Color(255, 153, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("LINEA DE CREDITO");

        jPanel6.setBackground(new java.awt.Color(88, 147, 191));

        btnListadoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listado_32.png"))); // NOI18N
        btnListadoClientes.setText("      LISTADO CLIENTES");
        btnListadoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoClientesActionPerformed(evt);
            }
        });

        BtnRegistroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registro_32.png"))); // NOI18N
        BtnRegistroClientes.setText("      REGISTRO CLIENTES");
        BtnRegistroClientes.setActionCommand("REGISTRO CLIENTES");
        BtnRegistroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistroClientesActionPerformed(evt);
            }
        });

        BtnModCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar32.png"))); // NOI18N
        BtnModCliente.setText("      MODIFICAR CLIENTE");
        BtnModCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModClienteActionPerformed(evt);
            }
        });

        btnEliminar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir32.png"))); // NOI18N
        btnEliminar2.setText("        SALIR");
        btnEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar2ActionPerformed(evt);
            }
        });

        BtnUltimosPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/last_32.png"))); // NOI18N
        BtnUltimosPagos.setText("      ULTIMOS PAGOS");
        BtnUltimosPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUltimosPagosActionPerformed(evt);
            }
        });

        BtnBusquedaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar_32.png"))); // NOI18N
        BtnBusquedaCliente.setText("      BUSQUEDA CLIENTE");
        BtnBusquedaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBusquedaClienteActionPerformed(evt);
            }
        });

        btnAbonos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar_32.png"))); // NOI18N
        btnAbonos.setText("      INGRESAR ABONOS");
        btnAbonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbonosActionPerformed(evt);
            }
        });

        btnAbonos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar2_32.png"))); // NOI18N
        btnAbonos1.setText("      MODIFICAR ABONOS");
        btnAbonos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbonos1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAbonos1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BtnUltimosPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnModCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnRegistroClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListadoClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnBusquedaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAbonos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnRegistroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnModCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnBusquedaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListadoClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAbonos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAbonos1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnUltimosPagos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jInternalFrame2.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame2.setVisible(true);

        jPanel1.setBackground(new java.awt.Color(56, 98, 127));

        JPanelcambianteLineaCredito.setBackground(new java.awt.Color(88, 147, 191));

        javax.swing.GroupLayout JPanelcambianteLineaCreditoLayout = new javax.swing.GroupLayout(JPanelcambianteLineaCredito);
        JPanelcambianteLineaCredito.setLayout(JPanelcambianteLineaCreditoLayout);
        JPanelcambianteLineaCreditoLayout.setHorizontalGroup(
            JPanelcambianteLineaCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );
        JPanelcambianteLineaCreditoLayout.setVerticalGroup(
            JPanelcambianteLineaCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanelcambianteLineaCredito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanelcambianteLineaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
            .addComponent(jInternalFrame2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListadoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoClientesActionPerformed
                JPanelListadoClienteCredito nu=new JPanelListadoClienteCredito();
                //sql.CargarTablaClientes(4, "");
                nu.setSize(800,600);
                nu.setLocation(5,5);
                JPanelcambianteLineaCredito.removeAll();
                JPanelcambianteLineaCredito.add(nu,BorderLayout.CENTER);
                JPanelcambianteLineaCredito.revalidate();
                JPanelcambianteLineaCredito.repaint();
    }//GEN-LAST:event_btnListadoClientesActionPerformed

    private void BtnRegistroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistroClientesActionPerformed
                JPanelNuevoClienteCredito nu=new JPanelNuevoClienteCredito();
                nu.setSize(800,600);
                nu.setLocation(5,5);
                JPanelcambianteLineaCredito.removeAll();
                JPanelcambianteLineaCredito.add(nu,BorderLayout.CENTER);
                JPanelcambianteLineaCredito.revalidate();
                JPanelcambianteLineaCredito.repaint();
    }//GEN-LAST:event_BtnRegistroClientesActionPerformed

    private void BtnModClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModClienteActionPerformed
                JPanelModClienteCredito nu=new JPanelModClienteCredito();
                nu.setSize(800,600);
                nu.setLocation(5,5);
                JPanelcambianteLineaCredito.removeAll();
                JPanelcambianteLineaCredito.add(nu,BorderLayout.CENTER);
                JPanelcambianteLineaCredito.revalidate();
                JPanelcambianteLineaCredito.repaint();
    }//GEN-LAST:event_BtnModClienteActionPerformed

    private void btnEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar2ActionPerformed
        dispose();
    }//GEN-LAST:event_btnEliminar2ActionPerformed

    private void BtnUltimosPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUltimosPagosActionPerformed
        //        JPanelListadoClienteCredito nu=new JPanelListadoClienteCredito();
        //        sql.CargarTablaClientes(4, "");
        //        nu.setSize(800,600);
        //        nu.setLocation(5,5);
        //        JPanelcambianteLineaCredito.removeAll();
        //        JPanelcambianteLineaCredito.add(nu,BorderLayout.CENTER);
        //        JPanelcambianteLineaCredito.revalidate();
        //        JPanelcambianteLineaCredito.repaint();
    }//GEN-LAST:event_BtnUltimosPagosActionPerformed

    private void BtnBusquedaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBusquedaClienteActionPerformed
                JPanelBusquedaCliente nu=new JPanelBusquedaCliente();
                nu.setSize(800,600);
                nu.setLocation(5,5);
                JPanelcambianteLineaCredito.removeAll();
                JPanelcambianteLineaCredito.add(nu,BorderLayout.CENTER);
                JPanelcambianteLineaCredito.revalidate();
                JPanelcambianteLineaCredito.repaint();
                //sql.CargarTablaClientes(1, "");
    }//GEN-LAST:event_BtnBusquedaClienteActionPerformed

    private void btnAbonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbonosActionPerformed
                JPanelIngresoAbonos nu=new JPanelIngresoAbonos();
                nu.setSize(800,600);
                nu.setLocation(1,1);
                JPanelcambianteLineaCredito.removeAll();
                JPanelcambianteLineaCredito.add(nu,BorderLayout.CENTER);
                JPanelcambianteLineaCredito.revalidate();
                JPanelcambianteLineaCredito.repaint();
    }//GEN-LAST:event_btnAbonosActionPerformed

    private void btnAbonos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbonos1ActionPerformed
        //        JPanelModAbonos nu=new JPanelModAbonos();
        //        nu.setSize(800,600);
        //        nu.setLocation(1,1);
        //        JPanelcambianteLineaCredito.removeAll();
        //        JPanelcambianteLineaCredito.add(nu,BorderLayout.CENTER);
        //        JPanelcambianteLineaCredito.revalidate();
        //        JPanelcambianteLineaCredito.repaint();
    }//GEN-LAST:event_btnAbonos1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnBusquedaCliente;
    public javax.swing.JButton BtnModCliente;
    public javax.swing.JButton BtnRegistroClientes;
    public javax.swing.JButton BtnUltimosPagos;
    public static javax.swing.JPanel JPanelcambianteLineaCredito;
    public javax.swing.JButton btnAbonos;
    public javax.swing.JButton btnAbonos1;
    public javax.swing.JButton btnEliminar2;
    public javax.swing.JButton btnListadoClientes;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
